# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9aea41d456759aacafc2ad64afcd085d95f33b4d87814f8811d98c683d8e569b7b7efcaa552e198f72077de92c0fc5b9949737a613c4215e0503c1108619fd84

test:
  secret_key_base: 6e58b99863cd70cd3497514a4df455313b2cd0700f4edd2fb1bad3b6c01900228cf9adfccb11e0c21bebf601189b76f21f975d01ca4129ee62c8947282f36874

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
